export const upgrades = [
    { id: "stronger_click", name: "Сила щелчка", description: "Удваивает силу каждого щелчка", cost: 50, purchased: false, effect: () => { game.clickPower *= 2; }, unlocked: true, justUnlocked: false },
    { id: "faster_candles", name: "Темные свечи", description: "Удваивает производство свечей", cost: 200, purchased: false, effect: () => { game.generators.find((g) => g.id === "candle").multiplier *= 2; }, requirement: () => game.generators.find((g) => g.id === "candle").count >= 5, unlocked: false, justUnlocked: false },
    { id: "ancient_rituals", name: "Древние ритуалы", description: "Удваивает производство алтарей", cost: 1000, purchased: false, effect: () => { game.generators.find((g) => g.id === "altar").multiplier *= 2; }, requirement: () => game.generators.find((g) => g.id === "altar").count >= 5, unlocked: false, justUnlocked: false },
    { id: "forbidden_knowledge", name: "Запретные знания", description: "Удваивает производство гримуаров", cost: 11000, purchased: false, effect: () => { game.generators.find((g) => g.id === "grimoire").multiplier *= 2; }, requirement: () => game.generators.find((g) => g.id === "grimoire").count >= 5, unlocked: false, justUnlocked: false },
    { id: "awakened_spirits", name: "Пробужденные духи", description: "Удваивает производство склепов", cost: 120000, purchased: false, effect: () => { game.generators.find((g) => g.id === "crypt").multiplier *= 2; }, requirement: () => game.generators.find((g) => g.id === "crypt").count >= 5, unlocked: false, justUnlocked: false },
    { id: "dark_pact", name: "Тёмный пакт", description: "Удваивает производство некромантов", cost: 1300000, purchased: false, effect: () => { game.generators.find((g) => g.id === "necromancer").multiplier *= 2; }, requirement: () => game.generators.find((g) => g.id === "necromancer").count >= 5, unlocked: false, justUnlocked: false },
    { id: "cathedral_power", name: "Мощь собора", description: "Удваивает производство соборов", cost: 15000000, purchased: false, effect: () => { game.generators.find((g) => g.id === "cathedral").multiplier *= 2; }, requirement: () => game.generators.find((g) => g.id === "cathedral").count >= 5, unlocked: false, justUnlocked: false },
    { id: "abyss_call", name: "Зов Бездны", description: "Удваивает производство порталов", cost: 250000000, purchased: false, effect: () => { game.generators.find((g) => g.id === "abyss_portal").multiplier *= 2; }, requirement: () => game.generators.find((g) => g.id === "abyss_portal").count >= 5, unlocked: false, justUnlocked: false },
    { id: "soulforge_boost", name: "Усиление кузницы", description: "Удваивает производство кузниц душ", cost: 3500000000, purchased: false, effect: () => { game.generators.find((g) => g.id === "soulforge").multiplier *= 2; }, requirement: () => game.generators.find((g) => g.id === "soulforge").count >= 5, unlocked: false, justUnlocked: false },
    { id: "click_frenzy", name: "Клик-ярость", description: "Утрояет силу кликов", cost: 5000, purchased: false, effect: () => { game.clickPower *= 3; }, requirement: () => game.totalClicks >= 500, unlocked: false, justUnlocked: false },
    { id: "generator_synergy", name: "Синергия генераторов", description: "Каждый генератор увеличивает производство на 2%", cost: 100000, purchased: false, effect: () => { game.generators.forEach((g) => g.multiplier *= 1 + 0.02 * game.generators.reduce((sum, gen) => sum + gen.count, 0)); }, requirement: () => game.totalEssence >= 500000, unlocked: false, justUnlocked: false },
    { id: "soul_touch", name: "Касание душ", description: "Клики дают +5% от производства в секунду", cost: 250000, purchased: false, effect: () => { game.clickPower += calculateEssencePerSecond() * 0.05; }, requirement: () => game.totalClicks >= 2000, unlocked: false, justUnlocked: false },
    { id: "ghostly_aura", name: "Призрачная аура", description: "Увеличивает производство всех генераторов на 25%", cost: 50000, purchased: false, effect: () => { game.generators.forEach((g) => g.multiplier *= 1.25); }, requirement: () => game.totalEssence >= 100000, unlocked: false, justUnlocked: false },
    { id: "soul_storm", name: "Шторм душ", description: "Клики дают +10% от эссенции в секунду", cost: 750000, purchased: false, effect: () => { game.clickPower += calculateEssencePerSecond() * 0.1; }, requirement: () => game.totalClicks >= 5000, unlocked: false, justUnlocked: false },
    { id: "eternal_cycle", name: "Вечный цикл", description: "Увеличивает силу всех улучшений за души на 15%", cost: 1000000, purchased: false, effect: () => { game.prestigeUpgrades.forEach((u) => u.level > 0 && u.effect(u.level * 1.15)); }, requirement: () => game.totalPrestiges >= 5, unlocked: false, justUnlocked: false },
    // Новые улучшения для кликов
    { id: "click_novice", name: "Начинающий кликер", description: "Удваивает силу кликов за 1000 кликов", cost: 1000, purchased: false, effect: () => { game.clickPower *= 2; }, requirement: () => game.totalClicks >= 1000, unlocked: false, justUnlocked: false },
    { id: "click_adept", name: "Адепт кликов", description: "Утрояет силу кликов за 5000 кликов", cost: 50000, purchased: false, effect: () => { game.clickPower *= 3; }, requirement: () => game.totalClicks >= 5000, unlocked: false, justUnlocked: false },
    { id: "click_master_new", name: "Мастер кликов", description: "Увеличивает силу кликов в 5 раз за 10000 кликов", cost: 250000, purchased: false, effect: () => { game.clickPower *= 5; }, requirement: () => game.totalClicks >= 10000, unlocked: false, justUnlocked: false }
];